Desktop/pet_new/pet/accounts/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView

from pet.accounts.views import UserLoginView, ProfileDetailsView, UserRegisterView, ChangeUserPasswordView, \
    UserLogoutView, EditProfileView, DeleteProfileView

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login user'),
    path('profile/<int:pk>/', ProfileDetailsView.as_view(), name='profile details'),
    path('profile/create/', UserRegisterView.as_view(), name='create profile'),
    path('edit-password/', ChangeUserPasswordView.as_view(), name='change password'),
    path('password_change_done/', RedirectView.as_view(url=reverse_lazy('dashboard')), name='password_change_done'),
    path('logout/', UserLogoutView.as_view(), name = 'logout form'),
    path('profile/edit/<int:pk>/', EditProfileView.as_view(), name='edit profile'),
    path('profile/delete/<int:pk>/', DeleteProfileView.as_view(), name='delete profile'),

]

Desktop/pet_new/pet/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from pet import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pet.main.urls')),
    path('accounts/', include('pet.accounts.urls')),
] + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/pet_new/pet/accounts/models.py
from django.contrib.auth import models as auth_models
from django.core.validators import MinLengthValidator
from django.db import models

from pet.accounts.managers import PetstagramUserManager
from pet.common.validators import only_letters_validator


class PetstagramUser(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):

    USERNAME_MAX_LENGTH = 25

    username = models.CharField(
        max_length=USERNAME_MAX_LENGTH,
        unique=True,
    )

    date_joined = models.DateTimeField(
        auto_now_add=True,
    )

    is_staff = models.BooleanField(
        default=False,
    )

    USERNAME_FIELD = 'username'
    objects = PetstagramUserManager()

#This way the superuser wont have a profile. The easiest solution: from admin panel create profile and associates it
#with the superuser (otherwise 'superuser profile details page' cant show)

class Profile(models.Model):
    FIRST_NAME_MIN_LENGTH = 2
    FIRST_NAME_MAX_LENGTH = 30
    LAST_NAME_MIN_LENGTH = 2
    LAST_NAME_MAX_LENGTH = 30

    MALE = 'male'
    FEMALE = 'female'
    DO_NOT_SHOW = 'Do not show'

    GENDERS = [(x,x) for x in (MALE, FEMALE, DO_NOT_SHOW)]

    first_name = models.CharField(
        max_length=FIRST_NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(FIRST_NAME_MIN_LENGTH),
            only_letters_validator,
        )

    )

    last_name = models.CharField(
        max_length=LAST_NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(LAST_NAME_MIN_LENGTH),
            only_letters_validator,
        )
    )

    picture = models.URLField()

    date_of_birth = models.DateField(
        null=True,
        blank=True,
    )

    description=models.TextField(
        null=True,
        blank=True,
    )

    email=models.EmailField(
        null=True,
        blank=True,
    )

    gender=models.CharField(
        max_length=max(len(x) for x, _ in GENDERS),
        choices=GENDERS,
        default=DO_NOT_SHOW
    )

    user = models.OneToOneField(
        PetstagramUser,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

Desktop/pet_new/pet/accounts/forms.py
from datetime import date

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from pet.accounts.models import Profile
from pet.common.view_mixins import BootstrapFormMixin
from django import forms

from pet.main.models import PetPhoto, Pet

UserModel = get_user_model()

class CreateProfileForm(BootstrapFormMixin, UserCreationForm):

    first_name = forms.CharField(
        max_length = Profile.FIRST_NAME_MAX_LENGTH,
    )

    last_name = forms.CharField(
        max_length=Profile.LAST_NAME_MAX_LENGTH,
    )

    picture = forms.URLField()

    date_of_birth = forms.DateField()

    description = forms.CharField(
        widget=forms.Textarea
    )

    email = forms.EmailField()

    gender = forms.ChoiceField(
        choices=Profile.GENDERS
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_controls()

    def save(self, commit=True):
        user = super().save(commit=commit)
        profile = Profile(
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            picture=self.cleaned_data['picture'],
            date_of_birth=self.cleaned_data['date_of_birth'],
            description=self.cleaned_data['description'],
            email=self.cleaned_data['email'],
            gender=self.cleaned_data['gender'],
            user=user,
        )
        if commit:
            profile.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'picture', 'description')
        widgets={
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter first name'
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter last name'
                }
            ),
            'picture': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter URL'
                }
            ),
        }

class EditProfileForm(forms.ModelForm):
    MIN_DATE_OF_BIRTH = date(1920, 1, 1)
    MAX_DATE_OF_BIRTH = date.today()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial['gender']=Profile.DO_NOT_SHOW

    def clean_date_of_birth(self):
        date_of_birth = self.cleaned_data['date_of_birth']
        if date_of_birth < self.MIN_DATE_OF_BIRTH or self.MAX_DATE_OF_BIRTH < date_of_birth:
            raise ValidationError(f'Date of birth must be between {self.MIN_DATE_OF_BIRTH} and {self.MAX_DATE_OF_BIRTH}')
        return date_of_birth

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'picture', 'date_of_birth', 'email', 'gender', 'description')
        widgets={
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter first name',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter last name',
                }
            ),
            'picture': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter URL',
                }
            ),
            'date_of_birth': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    # 'min': '1920-01-01',
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter email',
                }
            ),
            'gender': forms.Select(
                choices=Profile.GENDERS,
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Enter description',
                    'rows': 3,
                }
            ),

        }

class DeleteProfileForm(forms.ModelForm):
    def save(self, commit = True):
        user = UserModel.objects.get(pk=self.instance.user_id)
        PetPhoto.objects.filter(user=user).delete()
        Pet.objects.filter(user=user).delete()
        self.instance.delete()
        user.delete()
        return self.instance

    class Meta:
        model=Profile
        fields=()

Desktop/pet_new/pet/accounts/views.py
from django.contrib.auth import views as views
from django.contrib.auth.views import PasswordChangeView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView

from pet.accounts.forms import CreateProfileForm, EditProfileForm, DeleteProfileForm
from pet.accounts.models import Profile
from pet.common.view_mixins import RedirectToDashboard
from pet.main.models import Pet, PetPhoto


class UserLoginView(views.LoginView):
    template_name = 'accounts/login_page.html'
    success_url = reverse_lazy('dashboard')

    def get_success_url(self):
        if self.success_url:
            return self.success_url
        return super().get_success_url()

class UserRegisterView(RedirectToDashboard, CreateView):
    form_class = CreateProfileForm
    template_name = 'accounts/profile_create.html'
    success_url = reverse_lazy('dashboard')

class ProfileDetailsView(DetailView):
    model = Profile
    template_name = 'accounts/profile_details.html'
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pets = Pet.objects.filter(user_id=self.object.user_id)

        pet_photos = PetPhoto.objects \
            .filter(user_id=self.object.user_id) \
            .distinct()

        total_pet_photos_count = len(pet_photos)
        total_likes_count = 0
        for pt_photo in pet_photos:
            total_likes_count += len(pt_photo.like_set.all())

        context.update({
            'total_likes_count': total_likes_count,
            'pets': pets,
            'total_pet_photos_count': total_pet_photos_count,
            'is_owner': self.object.user_id == self.request.user.id
        })
        return context

class ChangeUserPasswordView(PasswordChangeView):
    template_name = 'accounts/change_password.html'

class UserLogoutView(LogoutView):
    next_page = reverse_lazy('index')

class EditProfileView(UpdateView):
    form_class = EditProfileForm
    model = Profile
    template_name = 'accounts/profile_edit.html'

    def get_success_url(self):
        return reverse_lazy('profile details',  kwargs={'pk': self.object.pk})

class DeleteProfileView(UpdateView):
    form_class = DeleteProfileForm
    model = Profile
    template_name = 'accounts/profile_delete.html'
    success_url = reverse_lazy('index')

Desktop/pet_new/templates/accounts/change_password.html
{% extends 'base.html' %}


{% block page_content %}
<div class="container mb-5">
    <h1 class="text-center">Login to Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

            <!-- Login Form -->
            <form method="post" action="{% url 'change password' %}">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary mt-2" type="submit">Change</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="col-lg-3"></div>
    </div>
</div>
{% endblock %}

{#<!-- Page Footer -->#}
{#<footer class="fixed-bottom card-footer ">#}
{#    <div>@2022 Python Web Basics Workshop at SoftUni</div>#}
{#</footer>#}
{#<!-- End Page Footer -->#}
{##}
{#</body>#}
{##}
{#<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"#}
{#        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"#}
{#        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"#}
{#        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"#}
{#        crossorigin="anonymous"></script>#}
{##}
{#</html>#}

Desktop/pet_new/templates/accounts/home_page.html
{% extends 'base.html' %}


{% block page_content %}
    <div class="jumbotron">
        <img style="width: 100%"
             src="https://activepets.co.za/web/ap-content/uploads/2019/08/Active-pets-dogs-and-cats.png" alt="">
        <div class="position-sticky">
            <h1 class="display-4">Welcome to Petstagram</h1>
            <p class="lead">Share your pets photos.</p>
            <hr class="my-4">
            <div class="flex-row">

                <!-- Login Button -->
                <a href="{% url 'login user' %}" class="btn btn-lg btn-secondary">Login</a>

                <!-- Register Button -->
                <a href="#" class="btn btn-lg btn-secondary">Register</a>
            </div>
        </div>
    </div>
{% endblock %}

Desktop/pet_new/templates/accounts/login_page.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{##}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Petstagram</title>#}
{##}
{#    <!-- Bootstrap CSS -->#}
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"#}
{#          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">#}
{#    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">#}
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"#}
{#          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">#}
{#</head>#}
{##}
{#<body>#}
{##}
{#<!-- Navigation Bar -->#}
{#<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">#}
{#    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"#}
{#            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">#}
{#        <span class="navbar-toggler-icon"></span>#}
{#    </button>#}
{#    <div class="collapse navbar-collapse" id="navbarNavDropdown">#}
{#        <ul class="navbar-nav">#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="#">Home</a>#}
{#            </li>#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="#">Dashboard</a>#}
{#            </li>#}
{#        </ul>#}
{#    </div>#}
{#</nav>#}
{#<!-- End Navigation Bar -->#}

{% extends 'base.html' %}


{% block page_content %}
<div class="container mb-5">
    <h1 class="text-center">Login to Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">

            <!-- Login Form -->
            <form method="POST">
                {% csrf_token %}
                {{ form }}
                <button class="btn btn-primary mt-2" type="submit">Log in</button>
            </form>
            <!-- End Login Form -->

        </div>
        <div class="col-lg-3"></div>
    </div>
</div>
{% endblock %}

{#<!-- Page Footer -->#}
{#<footer class="fixed-bottom card-footer ">#}
{#    <div>@2022 Python Web Basics Workshop at SoftUni</div>#}
{#</footer>#}
{#<!-- End Page Footer -->#}
{##}
{#</body>#}
{##}
{#<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"#}
{#        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"#}
{#        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"#}
{#        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"#}
{#        crossorigin="anonymous"></script>#}
{##}
{#</html>#}

Desktop/pet_new/templates/accounts/profile_create-old.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Petstagram</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="https://pluspng.com/img-png/instagram-png-instagram-png-icon-1024.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:2%">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index-page' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'profile-page' %}">Profile</a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    <h1 class="text-center">Create Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form>
                <div class="form-group">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" name="first_name" maxlength="30" required
                           placeholder="Enter first name" id="first_name"/>
                </div>
                <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    <input type="text" class="form-control" name="last_name" maxlength="30" required
                           placeholder="Enter last name" id="id_last_name"/>
                </div>
                <div class="form-group">
                    <label for="id_image">Link to Profile Image</label>
                    <input type="url" class="form-control" name="profile_image" required id="id_image"
                    placeholder="Enter URL"/>
                </div>
                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
</div>

<!-- Page Footer -->
<footer class="fixed-bottom card-footer ">
    <div>@2022 Python Web Basics Workshop at SoftUni</div>
</footer>
<!-- End Page Footer -->

</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
        integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
        integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
        crossorigin="anonymous"></script>

</html>

Desktop/pet_new/templates/accounts/profile_create.html
{% extends 'base.html' %}


{% block page_content %}
    <h1 class="text-center">Create Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="POST" action="{% url 'create profile' %}">

                {% csrf_token %}
                {{ form }}

                <button class="btn btn-primary mt-2" type="submit">Create</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
{% endblock %}

Desktop/pet_new/templates/accounts/profile_delete.html
{% extends 'base.html' %}


{% block page_content %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Are you sure you want to delete your profile?</h1>
            <div class="m-auto d-flex justify-content-center">
                <div class="m-2">
                    <form method="post" action="{% url 'delete profile' profile.pk %}">
                        {% csrf_token %}
                        {{ form }}

                        <input type="submit" value="Confirm" class="btn btn-danger"/>
                    </form>
                </div>
                <div class="m-2">
                    <a class="btn btn-primary" href="javascript:history.back()">No, go back</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Desktop/pet_new/templates/accounts/profile_details.html
{% extends 'base.html' %}


{% block page_content %}
    <div class="row justify-content-center">
        <div class="d-flex">
            <div class="d-inline p-2 w-50">
                <img src="{{ profile.picture }}"
                     class="w-50 rounded mx-auto d-block" alt="description">
            </div>
            <div class="d-inline p-2 w-50">
                <div class="d-flex flex-column">
                    <h5><u>Name:</u> {{ profile.first_name }} {{ profile.last_name }}</h5>
                    <!-- If Date of Birth -->
                    {% if profile.date_of_birth %}
                        <h5><u>Birthdate:</u> {{ profile.date_of_birth }}</h5>
                    {% endif %}
                    <!-- If Email -->
                    {% if profile.email %}
                        <h5><u>Email:</u> {{ profile.email }}</h5>
                    {% endif %}
                    <!-- If Gender is Chosen -->
                    <h5><u>Gender:</u> {{ profile.gender }}</h5>
                    <!-- If Description -->
                    {% if profile.description %}
                        <h5><u>Description:</u> {{ profile.description }}</h5>
                    {% endif %}
                </div>
                <p class="mt-2">Total Images: {{ total_pet_photos_count }}</p>
                <p class="mt-2">Total Likes: {{ total_likes_count }}</p>
                {% if is_owner %}
                    <a href="{% url 'edit profile' profile.pk %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'delete profile' profile.pk %}" class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
        </div>
    </div>

<!-- End Profile Information -->

<!-- Pets Information -->
<h2 class="text-center">My Pets</h2>
<div class="container mb-4">
    <div class="d-flex justify-content-start mb-5">
    {% for pet in pets %}
        <!-- Info for First Pet -->
        <div style="width: 18rem;">
            <h5>{{ pet.name }}</h5>
            {% if pet.date_of_birth %}
                <p class="mt-2">Age: {{ pet.age }}</p>
            {% endif %}
{#        {% if is_owner %}#}
{#            <a href="{% url 'edit pet' pet.pk %}" class="btn btn-primary">Edit</a>#}
{#            <a href="{% url 'delete pet' pet.pk %}" class="btn btn-danger">Delete</a>#}
{#        {% endif %}#}
        </div>
     {% endfor %}
    </div>
</div>

{% endblock %}

Desktop/pet_new/templates/accounts/profile_edit.html
{% extends 'base.html' %}


{% block page_content %}
    <h1 class="text-center">Edit Your Profile</h1>
    <div class="row">
        <div class="col-lg-3"></div>
        <div class="col-lg-6">
            <form method="POST" action="{% url 'edit profile' profile.pk %}">
                {% csrf_token %}

               {{ form}}

                <button class="btn btn-primary mt-2" type="submit">Edit</button>
            </form>
        </div>
        <div class="col-lg-3"></div>
    </div>
    <p></p>
    <p></p>
    <p></p>
{% endblock %}